name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - run: pnpm install
      - run: pnpm -r run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        app:
          - {
              name: 'next-auth',
              path: './apps/next-auth/dist/',
              remote_path: '/var/www/guias/next-auth/',
            }
          - {
              name: 'teste',
              path: './apps/teste/dist/',
              remote_path: '/var/www/guias/teste/',
            }
          # Add more apps as needed
          steps:
            run: echo ls -la
            run: echo $PWD
            run: echo ${{ matrix.app.path }}
            run: echo ${{ matrix.app.remote_path }}

            - name: Deploy with rsync
            uses: burnett01/rsync-deployments@5.2
            with:
              switches: -avzr --quiet --delete
              path: ${{ matrix.app.path }}
              remote_path: ${{ matrix.app.remote_path }}
              remote_host: ${{ secrets.HOST }}
              remote_user: ${{ secrets.USERNAME }}
              remote_key: ${{ secrets.SSH_KEY }}
            - name: Console current folder
            run: echo $PWD
