name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Cache Next.js build files
        uses: actions/cache@v4
        with:
          path: apps/home/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Cache Astro build files
        uses: actions/cache@v4
        with:
          path: |
            apps/next-auth/node_modules/.astro
            apps/next-introdutorio/node_modules/.astro
            apps/next-intermediario/node_modules/.astro
            apps/ts-no-react/node_modules/.astro
            apps/zod/node_modules/.astro
            apps/react-hook-form/node_modules/.astro
            apps/react-intro/node_modules/.astro
            apps/tailwindcss/node_modules/.astro
          key: ${{ runner.os }}-astro-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-astro-

      - run: pnpm install

      - name: Build Projects
        run: pnpm -r run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            apps/home/dist/
            apps/next-auth/dist/
            apps/next-introdutorio/dist/
            apps/next-intermediario/dist/
            apps/ts-no-react/dist/
            apps/zod/dist/
            apps/react-hook-form/dist/
            apps/react-intro/dist/
            apps/tailwindcss/dist/
          # Add more apps as needed

  deploy:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        app:
          - name: 'home'
            path: './home/dist/'
            remote_path: '/var/www/guias/home/'
          - name: 'next-auth'
            path: './next-auth/dist/'
            remote_path: '/var/www/guias/next-auth/'
          - name: 'next-introdutorio'
            path: './next-introdutorio/dist/'
            remote_path: '/var/www/guias/next-introdutorio/'
          - name: 'next-intermediario'
            path: './next-intermediario/dist/'
            remote_path: '/var/www/guias/next-intermediario/'
          - name: 'ts-no-react'
            path: './ts-no-react/dist/'
            remote_path: '/var/www/guias/ts-no-react/'
          - name: 'zod'
            path: './zod/dist/'
            remote_path: '/var/www/guias/zod/'
          - name: 'react-hook-form'
            path: './react-hook-form/dist/'
            remote_path: '/var/www/guias/react-hook-form/'
          - name: 'react-intro'
            path: './react-intro/dist/'
            remote_path: '/var/www/guias/react-intro/'
          - name: 'tailwindcss'
            path: './tailwindcss/dist/'
            remote_path: '/var/www/guias/tailwindcss/'
          # Add more apps as needed

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: List All Files after downloading artifacts (excluding node_modules)
        run: find . -type d -name node_modules -prune -o -type f -print

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --quiet --delete
          path: ${{ matrix.app.path }}
          remote_path: ${{ matrix.app.remote_path }}
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
